### ISSUE TITLE
incampatibility with Firefox Quantum

### ISSUE THREAD

**Issue by juhakivekas** [palant/jsdeobfuscator#10] opened 2017-11-23 15:13 UTC
I'm interested in doing something similar to what the deobfuscator does and I'd probably fork it, but right now the extension isn't installable on the newest Firefox versions. Do you plan to update the extension to being a WebExtension, or fixing whatever the reason for the incompatibility is? If not, then do you know why the deobfuscator isn't compatible with the newer versions?

I might want to look into using this as a base, but I'm a little unsure how much there is to do in order to get it working with newest versions of Firefox.

**Comment by palant** [comment] 2017-11-23 19:32
This is a duplicate of #9. In short: doing anything like that is no longer possible with Firefox 57.

**Closed by palant** 2017-11-23 19:32 UTC
