### ISSUE TITLE
[Feature request] syntax highlighting using CodeMirror

### ISSUE THREAD

**Issue by darkred** [palant/jsdeobfuscator#7] opened 2017-04-23 10:51 UTC
_(in continuance to [this thread](https://adblockplus.org/forum/viewtopic.php?f=5&t=8855))_

My suggestion is to display the code using CodeMirror's syntax highlighting.

[CodeMirror](http://codemirror.net/) is a popular HTML5-based code editor component used on web sites. It is customizable and theme-able. 
The Firefox Devtools have been using CodeMirror (in Style editor, Debugger, Inspector (Edit as HTML) and Scratchpad) since Firefox 27.

<br>

Currently, JavaScript Deobfuscator displays the running code using one font and a single color (black).

Syntax highlighting would improve the readability and context of the displayed code
(especially in conjunction with the code beautification feature that has been added since v2.0 of the extension).

**Comment by palant** [comment] 2017-04-23 11:07
While I might still find time to implement this change, JavaScript Deobfuscator is heading towards deprecation. The issue is, [starting with Firefox 57 (release date: November 14, 2017) classic extensions will no longer be allowed](https://blog.mozilla.org/addons/2016/11/23/add-ons-in-2017/). There is no way for JavaScript Deobfuscator to keep working, the necessary functionality simply isn't available via the Web Extensions platform.

**Comment by darkred** [comment] 2017-04-23 21:11
>  I might still find time to implement this change.

Thank you.

> JavaScript Deobfuscator is heading towards deprecation. The issue is, starting with Firefox 57 (release date: November 14, 2017) classic extensions will no longer be allowed. There is no way for JavaScript Deobfuscator to keep working, the necessary functionality simply isn't available via the Web Extensions platform.

Yes, I'm aware of that.
So, at that time, apart from having Firefox 57 as my main browser,
I'll also keep a Firefox 56 portable edition 
in order to be able to still use your great extension (and any others that will stop working then)

**Comment by palant** [comment] 2017-12-01 13:35
Resolving issue, the extension is officially deprecated now. I'm sorry but I didn't find time to work on this after all.

**Closed by palant** 2017-12-01 13:35 UTC
